# Generated by Django 2.2 on 2022-01-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartlist',
            old_name='cart_id',
            new_name='cr_id',
        ),
    ]
