# Generated by Django 2.2 on 2022-01-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart1', '0002_auto_20220107_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartlist',
            old_name='cr_id',
            new_name='cart_id',
        ),
    ]
